### ISSUE TITLE
Train File

### ISSUE THREAD

**Issue by ahkarami** [DavideA/c3d-pytorch#2]
Hi, 
thank you very much for contributing this neat C3D implementation in PyTorch.
Would you please upload your train code? 
Thank You

**Comment by DavideA** [comment]
Hi!

There is no training script at all :)
Weights were converted from [this keras porting](https://gist.github.com/albertomontesg/d8b21a179c1e6cca0480ebdf292c34d2), where in turn weights were converted from [the original caffe implementation](https://github.com/facebook/C3D).

D

**Comment by ahkarami** [comment]
OK, Thank you. However, I Suggest to implement the training code. It would be useful for other data sets.
