### ISSUE TITLE
Fail to load pre-trained model

### ISSUE THREAD

**Issue by YeTianJHU** [DavideA/c3d-pytorch#6]
Hi!

Thank you so much for your great work!
I have a issue when loading the pre-trained, even if just using your predict.py:

```
Traceback (most recent call last):
  File "predict.py", line 101, in <module>
    main()
  File "predict.py", line 81, in main
    net.load_state_dict(torch.load('c3d.pickle'))
  File "/home/ye/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 231, in load
    return _load(f, map_location, pickle_module)
  File "/home/ye/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 386, in _load
    deserialized_objects[key]._set_from_file(f, offset)
RuntimeError: unexpected EOF. The file might be corrupted.
```
It seems that the c3d.pickle may be corrupted. Could you check with that please?

Thank you so much! :)

**Comment by DavideA** [comment]
I'll surely check it as soon as I can!

Can you please report your version of pytorch?

**Comment by YeTianJHU** [comment]
I'm using anaconda python 2.7.13 + pytorch 0.2.0_4 + cuda 7.5. Thank you!

**Comment by DavideA** [comment]
Works fine with pytorch 0.3. But should work also with pytorch 0.2.

Are you sure nothing went wrong when downloading the weight file?

**Comment by YeTianJHU** [comment]
It works this time! There should be something wrong when downloading (although I also downloaded for several times before). Thank you so much!!!
