### ISSUE TITLE
How to load pickle file

### ISSUE THREAD

**Issue by cryptedp** [DavideA/c3d-pytorch#8]
Since I am trying to use the pretrained weights for a different dataset, I am trying to understand how to change the very last layer. However when I try to read the pickle file with only pickle.load() it only returns a integer. When I try to read the pickle file sequentially, it says that A load persistent id instruction was encountered,
but no persistent_load function was specified.

Since I don't know how the pickle file was generated, can you tell me how to read the pickle file in python, so I know what I can modify for my purposes ?

**Comment by DavideA** [comment]
Hi!
Can you please detail a little bit your needs?

You should never read the pickle file yourself, use torch.load instead.
Than you can act on the state_dict if you want to load weights for specific layers.

D

**Comment by DavideA** [comment]
Closing.
